# Generated by Django 4.0.6 on 2022-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_avatar_user_bio_user_blocked_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveIntegerField(null=True, verbose_name='phone_number'),
        ),
    ]
